name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  playwrighttests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.40.1-focal
      env:
        BASEURL: ${{ secrets.BASEURL }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        # BASEURL: https://app-cmo8zo3vh6q4.frontegg.com/oauth/account/login
        # USERNAME: vadim.yekovenko@gmail.com 
        # PASSWORD: PASSWORD=Qwerty1!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npx playwright test --grep @e2e --config ./playwright.config.ts