name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  playwrighttests:
    # timeout-minutes: 60
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.40.1-focal
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        # USERNAME: vadim.yekovenko@gmail.com 
        # PASSWORD: PASSWORD=Qwerty1!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "Start the app"
          npm run start &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run pw-e2e-ci