name: React app - build and deploy
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build the app
        run: npm run build
            
      - name: Deploy the app 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src
